/*
 * bibtex-entry.c — WASM entry point for BibTeX
 *
 * Exports compileBibtex() which calls bibtex's main() with the
 * appropriate arguments. The aux file basename is set via
 * setMainEntry() from the worker JS before calling compileBibtex().
 *
 * Built separately from pdfTeX to avoid web2c symbol conflicts.
 */

#include <stdio.h>
#include <string.h>

/* bibtex main() — generated by web2c from bibtex.web */
extern int main(int argc, char **argv);

static char main_entry[1024] = "main";

/* Called from JS before compileBibtex() to set the .aux basename */
int setMainEntry(const char *entry) {
    if (!entry) return -1;
    strncpy(main_entry, entry, sizeof(main_entry) - 1);
    main_entry[sizeof(main_entry) - 1] = '\0';
    /* Strip .aux extension if present */
    size_t len = strlen(main_entry);
    if (len > 4 && strcmp(main_entry + len - 4, ".aux") == 0) {
        main_entry[len - 4] = '\0';
    }
    return 0;
}

/*
 * Run bibtex on the current main_entry.
 * Expects main_entry.aux to exist in WORKROOT (/work/).
 * Produces main_entry.bbl and main_entry.blg.
 */
int compileBibtex(void) {
    char *argv[] = {
        "bibtex",
        main_entry,
        NULL
    };
    return main(2, argv);
}
