/**
 * LuaLaTeX warmup manifest — TeX Live files a cold first compile fetches.
 *
 * After the prebuilt-format fast path (no `compileformat`), the dominant cost of
 * a first LuaLaTeX compile is the worker fetching its runtime synchronously, one
 * file at a time, over the network (luaotfload + lualibs Lua runtime, font TFM/
 * OTF, …). The engine prefetches these in parallel (overlapping worker boot) and
 * injects them via `preloadtexlive`, so the worker finds them locally and never
 * blocks on sync XHR. Known-missing lookups are pre-seeded via `preload404`.
 *
 * GENERATED by scripts/gen-luatex-manifest.mjs — do not edit by hand. `dir` is
 * the CDN format directory (by file extension); `name` is the requested/saved
 * filename and `format` the kpse format number — both must match
 * `kpse_find_file_impl` so a preloaded file is a cache hit.
 */
export interface LuatexPreloadEntry {
    format: number;
    name: string;
    dir: string;
}
export interface LuatexNotFoundEntry {
    format: number;
    filename: string;
}
/** Files that return 200 and are fetched during a first compile (prefetch these). */
export declare const LUATEX_PRELOAD: LuatexPreloadEntry[];
/** Lookups that 404/403 during a first compile (pre-seed to skip wasted XHR). */
export declare const LUATEX_KNOWN_404: LuatexNotFoundEntry[];
