/**
 * Successful runtime lookups observed with article + fontspec and Latin Modern.
 * These are optional prefetch hints, never a negative lookup authority. Fetches
 * use the selected immutable mirror and failed requests remain demand-resolved.
 * Keep the requested name distinct from its resolved filename (Lua require and
 * OpenType lookups often omit the extension). No document-local input belongs here.
 */

export const XETEX_PRELOAD = [
  { format: 26, name: 'article.cls', dir: '26' },
  { format: 26, name: 'size10.clo', dir: '26' },
  { format: 47, name: 'lmroman10-regular', dir: '47', candidate: 'lmroman10-regular.otf' },
  { format: 26, name: 'xetexfontlist.txt', dir: '26' },
  { format: 26, name: 'fontspec.sty', dir: '26' },
  { format: 26, name: 'fontspec-xetex.sty', dir: '26' },
  { format: 26, name: 'fontenc.sty', dir: '26' },
  { format: 26, name: 'fontspec.cfg', dir: '26' },
  { format: 47, name: 'lmroman10-bold', dir: '47', candidate: 'lmroman10-bold.otf' },
  { format: 47, name: 'lmroman10-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman10-bolditalic.otf', dir: '47' },
  { format: 47, name: 'lmroman10-italic.otf', dir: '47' },
  { format: 47, name: 'lmroman10-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman12-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman12-italic.otf', dir: '47' },
  { format: 47, name: 'lmroman12-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman17-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman5-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman5-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman6-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman6-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman7-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman7-italic.otf', dir: '47' },
  { format: 47, name: 'lmroman7-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman8-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman8-italic.otf', dir: '47' },
  { format: 47, name: 'lmroman8-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman9-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman9-italic.otf', dir: '47' },
  { format: 47, name: 'lmroman9-regular.otf', dir: '47' },
  { format: 26, name: 'l3backend-xetex.def', dir: '26' },
  { format: 11, name: 'pdftex.map', dir: '11' },
  { format: 11, name: 'texglyphlist.txt', dir: '11' },
  { format: 11, name: 'pdfglyphlist.txt', dir: '11' },
  { format: 11, name: 'glyphlist.txt', dir: '11' },
  { format: 36, name: 'lmroman10-regular.otf', dir: '47' },
]

export const LUATEX_RUNTIME_PRELOAD = [
  { format: 51, name: 'ltluatex', dir: '51', candidate: 'ltluatex.lua' },
  { format: 51, name: 'luaotfload-main', dir: '51', candidate: 'luaotfload-main.lua' },
  { format: 51, name: 'luaotfload', dir: '51', candidate: 'luaotfload.lua' },
  { format: 51, name: 'lualibs', dir: '51', candidate: 'lualibs.lua' },
  { format: 51, name: 'luaotfload-status', dir: '51', candidate: 'luaotfload-status.lua' },
  { format: 51, name: 'luaotfload-scripts', dir: '51', candidate: 'luaotfload-scripts.lua' },
  { format: 51, name: 'luaotfload-unicode', dir: '51', candidate: 'luaotfload-unicode.lua' },
  { format: 51, name: 'lua-uni-case', dir: '51', candidate: 'lua-uni-case.lua' },
  { format: 51, name: 'lua-uni-parse', dir: '51', candidate: 'lua-uni-parse.lua' },
  { format: 51, name: 'luaotfload-realpath', dir: '51', candidate: 'luaotfload-realpath.lua' },
  { format: 51, name: 'lua-uni-normalize', dir: '51', candidate: 'lua-uni-normalize.lua' },
  { format: 51, name: 'luaotfload-arabic', dir: '51', candidate: 'luaotfload-arabic.lua' },
  {
    format: 51,
    name: 'luaotfload-harf-var-cff2',
    dir: '51',
    candidate: 'luaotfload-harf-var-cff2.lua',
  },
  {
    format: 51,
    name: 'luaotfload-harf-var-t2-writer',
    dir: '51',
    candidate: 'luaotfload-harf-var-t2-writer.lua',
  },
  {
    format: 51,
    name: 'luaotfload-harf-var-ttf',
    dir: '51',
    candidate: 'luaotfload-harf-var-ttf.lua',
  },
  { format: 51, name: 'luaotfload-bcp47', dir: '51', candidate: 'luaotfload-bcp47.lua' },
  { format: 51, name: 'expl3', dir: '51', candidate: 'expl3.lua' },
  { format: 51, name: 'lua-uni-stage-tables', dir: '51', candidate: 'lua-uni-stage-tables.lua' },
  { format: 47, name: 'lmroman10-regular', dir: '47', candidate: 'lmroman10-regular.otf' },
  { format: 51, name: 'fontspec', dir: '51', candidate: 'fontspec.lua' },
  { format: 47, name: 'lmroman10-bold', dir: '47', candidate: 'lmroman10-bold.otf' },
  { format: 47, name: 'lmroman10-regular.otf', dir: '47' },
  { format: 47, name: 'lmroman10-bolditalic.otf', dir: '47' },
  { format: 47, name: 'lmroman10-bold.otf', dir: '47' },
  { format: 47, name: 'lmroman10-italic.otf', dir: '47' },
  { format: 51, name: 'l3backend-luatex', dir: '51', candidate: 'l3backend-luatex.lua' },
]
