import { runRemoteBiber as x } from "./engine/biber-backend.js";
import { createBiberBackend as ue } from "./engine/biber-backend.js";
import { runRemoteBibliography as F, detectBibliographyMode as y, detectBiblatexBackend as w, parseBcfCitedKeys as E, generateBiblatexBbl as B, detectBiblatexSort as C, resolveBstFile as v } from "./engine/bibliography-backend.js";
import { BIBLIOGRAPHY_STAGE as ge, biblatexLiteBackend as be, selectBiblatexBackend as xe } from "./engine/bibliography-backend.js";
import { BibtexEngine as M } from "./engine/bibtex-engine.js";
import { createCompileEngine as S, unavailableEngineResult as I } from "./engine/compile-engine.js";
import { createCompletionSnapshot as D } from "./engine/completion-snapshot.js";
import { COMPLETION_SNAPSHOT_MAX_ESTIMATED_BYTES as ye, COMPLETION_SNAPSHOT_SCHEMA_VERSION as we } from "./engine/completion-snapshot.js";
import { buildIncrementalDependencyManifest as k, normalizeProjectDependencyPath as h, buildDependencyManifest as j } from "./engine/dependency-manifest.js";
import { resolveEngine as O } from "./engine/engine-select.js";
import { IncrementalCompiler as P } from "./engine/incremental.js";
import { detectIndexUse as u, runRemoteIndex as T } from "./engine/index-backend.js";
import { createMakeindexBackend as Be } from "./engine/index-backend.js";
import { MakeindexEngine as A } from "./engine/makeindex-engine.js";
import { buildDiagnostics as p, parseTexErrors as $ } from "./engine/parse-errors.js";
import { RerunController as R, signatureOf as U } from "./engine/rerun-controller.js";
import { WasmTexPdftexEngine as W } from "./engine/wasmtex-engine.js";
import { syncAllFilesToEngine as z } from "./fs/engine-sync.js";
import { VirtualFS as m } from "./fs/virtual-fs.js";
import { parseAuxFile as _ } from "./lsp/aux-parser.js";
import { rebuildBibIndex as K, parseBibFile as G } from "./lsp/bib-parser.js";
import { ProjectIndex as g } from "./lsp/project-index.js";
import { parseTraceFile as V } from "./lsp/trace-parser.js";
import { BIBER_STAGE as ve, BIBTEX_STAGE as Me, BackendRegistry as Se, INDEX_STAGE as Ie, createJsonTextBackend as De, createRemoteBackend as ke } from "./engine/backend-registry.js";
import { MemoryCacheStore as Oe, backendCacheKey as Pe, contentKey as Te, withCache as Ae } from "./engine/content-cache.js";
import { createXindyBackend as Re } from "./engine/xindy-backend.js";
function L(d) {
  return d ? d.endsWith("/") ? d : `${d}/` : "/";
}
class de {
  engine = null;
  engineKind = "pdflatex";
  detection = {
    engine: "pdflatex",
    reason: "default",
    forced: !1
  };
  /** Set when the document needs an engine whose artifact is not available. */
  unavailable = null;
  bibtexEngine = null;
  makeindexEngine = null;
  /** Incremental (checkpoint) compiler, set when `incremental` is on and the active
   *  engine is pdfLaTeX. Null otherwise (XeLaTeX/LuaLaTeX always do a full compile). */
  incremental = null;
  fs;
  projectIndex = new g();
  mainFile;
  assetBaseUrl;
  opts;
  initialized = !1;
  /** Outputs generated by auxiliary stages. They live in the VFS so LaTeX can read
   *  them, but are derived artifacts rather than host-editable project inputs. */
  generatedFiles = /* @__PURE__ */ new Set();
  /** Provenance is keyed by generated output so switching main files cannot attach
   *  one root's bibliography/index request to another root's derived artifact. */
  generatedDependencyObservations = /* @__PURE__ */ new Map();
  /** Stages attempted in the current compile, including failures with no output. */
  currentAuxiliaryDependencies = /* @__PURE__ */ new Map();
  /** The last successful full result's manifest seeds only the informational input
   *  list on an incremental result; the incremental manifest remains incomplete. */
  lastFullDependencyManifest;
  constructor(e = {}) {
    this.opts = e, this.mainFile = e.mainFile ?? "main.tex", this.assetBaseUrl = L(e.assetBaseUrl), this.fs = new m({ empty: !0 });
    for (const [i, t] of Object.entries(e.files ?? {}))
      this.fs.writeFile(i, t), this.updateIndexForFile(i, t);
  }
  /** Engine options shared by every engine kind (binary-specific bits are set
   *  by the factory). */
  engineBaseOpts() {
    const e = {
      assetBaseUrl: this.assetBaseUrl,
      skipFormatPreload: !!this.opts.skipFormatPreload,
      disablePreambleSnapshot: !!this.opts.disablePreambleSnapshot,
      persistentCache: !!this.opts.persistentCache,
      texliveVersion: this.opts.texliveVersion ?? "2025",
      ...this.opts.warmupCache ? { warmupCache: this.opts.warmupCache } : {}
    };
    return this.opts.texliveUrl && (e.texliveUrl = this.opts.texliveUrl), e;
  }
  /** Current main-file content as a string (for engine detection). */
  mainSource() {
    const e = this.fs.readFile(this.mainFile);
    return typeof e == "string" ? e : "";
  }
  /** All project `.tex` sources (path → content), for multi-file incremental compile. */
  projectTexFiles() {
    const e = /* @__PURE__ */ new Map();
    for (const i of this.fs.listFiles()) {
      if (!i.endsWith(".tex")) continue;
      const t = this.fs.readFile(i);
      typeof t == "string" && e.set(i, t);
    }
    return e;
  }
  /**
   * Ensure `this.engine` matches the engine the current main source requires.
   * On a kind change (or first call) it (re)creates and initializes the engine and
   * does a full resync. If a Unicode engine's artifact is unavailable, it records
   * `this.unavailable` instead of throwing (pdfLaTeX failures still throw).
   */
  async ensureEngine() {
    if (this.detection = O(this.mainSource(), this.opts.engine), !(this.engine && this.detection.engine === this.engineKind)) {
      this.engine?.terminate(), this.engineKind = this.detection.engine, this.engine = S(this.detection.engine, this.engineBaseOpts()), this.incremental = this.opts.incremental && this.engine instanceof W ? new P(this.engine, { mainFile: this.mainFile }) : null;
      try {
        await this.engine.init(), this.unavailable = null, await this.syncAllFilesToEngine();
      } catch (e) {
        if (this.detection.engine === "pdflatex") throw e;
        this.unavailable = this.detection;
      }
    }
  }
  async init() {
    this.initialized || (await this.ensureEngine(), this.initialized = !0);
  }
  async compile() {
    if (this.ensureInitialized(), this.currentAuxiliaryDependencies.clear(), await this.ensureEngine(), this.unavailable || !this.engine) {
      const s = I(this.unavailable ?? this.detection);
      return this.attachDependencyManifest(s), s;
    }
    const e = this.engine;
    if (await this.syncModifiedFilesToEngine(), e.setPreambleSnapshot) {
      const s = !this.opts.disablePreambleSnapshot && !u(this.mainSource());
      e.setPreambleSnapshot(s);
    }
    if (this.incremental) {
      const s = performance.now(), a = await this.incremental.tryIncremental(this.mainSource(), this.projectTexFiles());
      if (a?.final && a.pdf) return this.toCompileResult(a, performance.now() - s);
    }
    let i = await e.compile(), t = await this.runAuxStages(i);
    const n = new R();
    for (; (i.success || i.pdf) && !(!n.decide(
      i.log,
      U(i.semanticTrace ?? i.log)
    ).rerun && !t); )
      await this.syncModifiedFilesToEngine(), i = await e.compile(), t = await this.runAuxStages(i);
    return await this.updateMetadata(i), this.attachDependencyManifest(i), await this.attachCompletionSnapshot(i), this.incremental?.noteFull(this.mainSource(), this.projectTexFiles(), i.synctex), i;
  }
  /** Map an incremental (checkpoint) result to a CompileResult. The tail log carries this pass's
   *  diagnostics; head errors can't recur (the head is unchanged), and metadata/cross-refs are
   *  unchanged for a `final` result, so the last full compile's project index still holds. The raw
   *  `synctex` is null (the tail compiled in isolation), but `synctexData` carries the tail SyncTeX
   *  spliced onto the last full compile's head — exact for the spliced PDF (#99 P2). */
  toCompileResult(e, i) {
    const t = {
      success: e.success,
      pdf: e.pdf,
      log: e.log,
      errors: $(e.log),
      compileTime: Math.round(i),
      synctex: null,
      synctexData: e.synctexData ?? null,
      telemetry: { diagnostics: p(e.log) }
    };
    return t.telemetry.dependencyManifest = k(
      this.mainFile,
      this.lastFullDependencyManifest
    ), t;
  }
  setFile(e, i) {
    this.projectIndex.invalidateCompletionSnapshot(), this.fs.writeFile(e, i);
    const t = h(e) ?? e;
    if (this.generatedFiles.delete(t), this.generatedDependencyObservations.delete(t), this.currentAuxiliaryDependencies.clear(), (e.endsWith(".tex") || e.endsWith(".bib") || e.endsWith(".bst")) && !e.endsWith(".bbl")) {
      const n = this.mainFile.replace(/\.tex$/, "");
      this.dropGeneratedFile(`${n}.bbl`), this.dropGeneratedFile(`${n}.ind`);
    }
    e.endsWith(".tex") || this.incremental?.reset(), this.updateIndexForFile(e, i);
  }
  async loadProject(e) {
    this.fs = new m({ empty: !0 }), this.projectIndex = new g(), this.generatedFiles.clear(), this.generatedDependencyObservations.clear(), this.currentAuxiliaryDependencies.clear(), this.lastFullDependencyManifest = void 0, this.incremental?.reset();
    for (const [i, t] of Object.entries(e))
      this.fs.writeFile(i, t), this.updateIndexForFile(i, t);
    this.initialized && (this.bibtexEngine?.terminate(), this.bibtexEngine = null, this.makeindexEngine?.terminate(), this.makeindexEngine = null, this.engine && !this.unavailable ? (await this.engine.flushCache(), await this.syncAllFilesToEngine()) : (this.engine?.terminate(), this.engine = null));
  }
  getFile(e) {
    return this.fs.readFile(e);
  }
  listFiles() {
    return this.fs.listFiles();
  }
  getMainFile() {
    return this.mainFile;
  }
  setMainFile(e) {
    this.projectIndex.invalidateCompletionSnapshot(), this.mainFile = e, this.currentAuxiliaryDependencies.clear(), this.lastFullDependencyManifest = void 0, this.incremental?.setMainFile(e), this.initialized && this.engine && !this.unavailable && this.engine.setMainFile(e);
  }
  getProjectIndex() {
    return this.projectIndex;
  }
  getCompletionSnapshotState() {
    return this.projectIndex.getCompletionSnapshotState();
  }
  async readOutput(e) {
    return this.ensureInitialized(), await this.engine?.readFile(e) ?? null;
  }
  async flushCache() {
    this.ensureInitialized(), await this.engine?.flushCache();
  }
  /**
   * Clear the built-in persistent TeX Live asset cache (IndexedDB) for the
   * active TeX Live version. No-op when the persistent cache is unavailable.
   */
  async clearCache() {
    await this.engine?.clearCache();
  }
  dispose() {
    this.engine?.terminate(), this.engine = null, this.bibtexEngine?.terminate(), this.bibtexEngine = null, this.makeindexEngine?.terminate(), this.makeindexEngine = null, this.lastFullDependencyManifest = void 0, this.initialized = !1;
  }
  dropGeneratedFile(e) {
    this.fs.deleteFile(e);
    const i = h(e) ?? e;
    this.generatedFiles.delete(i), this.generatedDependencyObservations.delete(i);
  }
  auxiliaryDependencyObservations(e) {
    const i = new Map(this.currentAuxiliaryDependencies);
    for (const t of e.inputFiles ?? []) {
      const n = h(t);
      if (!n) continue;
      const s = this.generatedDependencyObservations.get(n);
      s && i.set(s.stage, s);
    }
    return [...i.values()];
  }
  /** Attach the manifest only here, above every engine and auxiliary backend. The
   * engine layer alone cannot distinguish host project files from generated VFS
   * artifacts or account for server/client stage requests. */
  attachDependencyManifest(e) {
    e.telemetry ??= { diagnostics: p(e.log) };
    const i = j({
      engine: this.engineKind,
      root: this.mainFile,
      projectFiles: this.fs.listFiles(),
      generatedFiles: this.generatedFiles,
      auxiliaryStages: this.auxiliaryDependencyObservations(e),
      result: e
    });
    e.telemetry.dependencyManifest = i, this.lastFullDependencyManifest = e.success && e.pdf ? i : void 0;
  }
  completionProfile() {
    const e = this.opts.texliveVersion ?? "2025";
    return {
      id: this.opts.completionProfile?.id ?? `wasmtex:${e}:${this.opts.texliveUrl ?? "default-mirror"}`,
      texliveYear: e,
      mirrorRevision: this.opts.completionProfile?.mirrorRevision ?? null
    };
  }
  async attachCompletionSnapshot(e) {
    if (!e.success || !this.engine || this.fs.getModifiedFiles().length > 0) return;
    const i = this.engine, t = this.mainFile, n = this.fs.listFiles().filter((r) => !this.generatedFiles.has(r)).flatMap((r) => {
      const o = this.fs.getFile(r);
      return o ? [
        {
          path: o.path,
          content: typeof o.content == "string" ? o.content : Uint8Array.from(o.content)
        }
      ] : [];
    }), s = i.getCompletionObservation?.(), a = await D({
      engine: this.engineKind,
      root: t,
      profile: this.completionProfile(),
      projectFiles: n,
      ...e.engineCommands ? { engineCommands: e.engineCommands } : {},
      engineCommandsComplete: e.engineCommandsComplete === !0,
      ...e.engineCommandsDropped !== void 0 ? { engineCommandsDropped: e.engineCommandsDropped } : {},
      ...s ? { engineObservation: s } : {},
      ...e.inputFiles ? { inputFiles: e.inputFiles } : {},
      inputFilesComplete: e.inputFilesComplete === !0
    });
    t !== this.mainFile || i !== this.engine || this.fs.getModifiedFiles().length > 0 || (e.telemetry ??= { diagnostics: p(e.log) }, e.telemetry.completionSnapshot = a, this.projectIndex.updateCompletionSnapshot(a));
  }
  async syncAllFilesToEngine() {
    const e = this.engine;
    !e || this.unavailable || await z(
      this.fs,
      e,
      (i) => this.ensureEngineDirectories(i),
      this.mainFile
    );
  }
  async syncModifiedFilesToEngine() {
    const e = this.engine;
    if (!e || this.unavailable) return;
    const i = this.fs.getModifiedFiles();
    await this.ensureEngineDirectories(i.map((t) => t.path));
    for (const t of i)
      await e.writeFile(t.path, t.content);
    this.fs.markSynced(i), e.setMainFile(this.mainFile);
  }
  async ensureEngineDirectories(e) {
    const i = this.engine;
    if (!i) return;
    const t = /* @__PURE__ */ new Set();
    for (const n of e) {
      const s = n.split("/");
      let a = "";
      for (let r = 0; r < s.length - 1; r++)
        a = a ? `${a}/${s[r]}` : s[r], t.add(a);
    }
    for (const n of Array.from(t).sort())
      await i.mkdir(n);
  }
  updateIndexForFile(e, i) {
    typeof i == "string" && (e.endsWith(".tex") && this.projectIndex.updateFile(e, i), e.endsWith(".bib") && this.updateBibIndex());
  }
  updateBibIndex() {
    K(this.fs, this.projectIndex);
  }
  async updateMetadata(e) {
    if (!this.engine) return;
    const i = this.mainFile.replace(/\.tex$/, ""), t = await this.engine.readFile(`${i}.aux`);
    if (t && this.projectIndex.updateAuxData(_(t)), e.engineCommands?.length && this.projectIndex.updateEngineCommands(e.engineCommands), e.semanticTrace && this.projectIndex.updateSemanticTrace(V(e.semanticTrace)), e.inputFiles?.length)
      for (const n of e.inputFiles) {
        const s = h(n);
        if (!s) continue;
        const a = this.fs.getFile(s);
        a && typeof a.content == "string" && this.projectIndex.updateFile(a.path, a.content);
      }
  }
  /** Run the auto aux stages (bibliography, then index) after a LaTeX pass. Returns whether
   *  any stage injected a new artifact this pass — if so the caller runs another LaTeX pass
   *  so the engine reads it (a `\printindex`-only document emits no rerun marker). A document
   *  is classic-BibTeX *or* biblatex (never both), so the two bibliography paths gate on
   *  mutually exclusive triggers and at most one fires. */
  async runAuxStages(e) {
    const i = await this.maybeRunBibtex(e) || await this.maybeRunBiblatex(e), t = await this.maybeRunMakeindex(e);
    return i || t;
  }
  /** @returns whether a fresh `.bbl` was injected this pass (forces one more LaTeX pass). */
  async maybeRunBibtex(e) {
    const i = this.engine;
    if (!i || !e.success && !e.pdf || !this.fs.listFiles().some((b) => b.endsWith(".bib"))) return !1;
    const t = this.mainFile.replace(/\.tex$/, ""), n = await i.readFile(`${t}.aux`);
    if (!n?.includes("\\citation{") || !n.includes("\\bibdata{") || this.fs.readFile(`${t}.bbl`)) return !1;
    const s = this.collectBibFiles(), a = { aux: n, bibFiles: s }, r = this.resolveProjectBst(n);
    r && (a.bstFiles = { [r.path]: r.content });
    const o = await F(this.opts.backends, a) ?? await this.runClientBibtex(t, n, s), l = {
      stage: "bibliography",
      projectInputs: [...Object.keys(s), ...Object.keys(a.bstFiles ?? {})],
      complete: !!o
    };
    if (this.currentAuxiliaryDependencies.set("bibliography", l), !o) return !1;
    const c = `${t}.bbl`, f = h(c) ?? c;
    return this.fs.writeFile(c, o), this.generatedFiles.add(f), this.generatedDependencyObservations.set(f, l), await i.writeFile(c, o), !0;
  }
  /**
   * The biblatex counterpart of {@link maybeRunBibtex}. A biblatex document does **not** write
   * the classic `\bibdata{}`/`\citation{}` markers to the `.aux` (it uses `\abx@aux@cite` and a
   * `.bcf` control file), so {@link maybeRunBibtex}'s gate never fires for it. Here we route the
   * `.bcf` the first LaTeX pass emitted: when `backend=biber` and a **server** Biber backend is
   * registered, run it on `{ bcf, bibFiles }` (full fidelity); otherwise fall back to the bundled
   * biblatex-lite (cite keys parsed from the `.bcf`, entries from the project `.bib`s). Inject the
   * `.bbl` so the next pass resolves `\cite`s.
   * @returns whether a fresh `.bbl` was injected this pass (forces one more LaTeX pass).
   */
  async maybeRunBiblatex(e) {
    const i = this.engine;
    if (!i || !e.success && !e.pdf) return !1;
    const t = this.mainSource();
    if (y(t) !== "biblatex") return !1;
    const n = this.mainFile.replace(/\.tex$/, "");
    if (this.fs.readFile(`${n}.bbl`)) return !1;
    const s = await i.readFile(`${n}.bcf`);
    if (!s?.trim()) return !1;
    const a = this.collectBibFiles(), r = (w(t) === "biber" ? await x(this.opts.backends, { bcf: s, bibFiles: a }) : null) ?? this.runClientBiblatexLite(t, s, a), o = {
      stage: "bibliography",
      projectInputs: Object.keys(a),
      complete: !!r
    };
    if (this.currentAuxiliaryDependencies.set("bibliography", o), !r) return !1;
    const l = `${n}.bbl`, c = h(l) ?? l;
    return this.fs.writeFile(l, r), this.generatedFiles.add(c), this.generatedDependencyObservations.set(c, o), await i.writeFile(l, r), !0;
  }
  /** Bundled biblatex-lite for the bibliography stage → `.bbl`: parse the cited keys from the
   *  `.bcf` and the entries from the project `.bib`s, then generate the documented-subset `.bbl`.
   *  The client default when no server Biber backend is registered (so a biblatex document still
   *  gets a bibliography fully on-device). */
  runClientBiblatexLite(e, i, t) {
    const n = Object.entries(t).flatMap(
      ([r, o]) => G(o, r)
    ), s = E(i), a = s.includes("*") ? n.map((r) => r.key) : s;
    return B({ entries: n, citedKeys: a, sort: C(e) });
  }
  /**
   * Auto-run the index stage for `\printindex` (analogous to {@link maybeRunBibtex}): when
   * the LaTeX pass emitted a non-empty `.idx` and no `.ind` exists yet, turn it into `.ind`
   * — via a registered **server** backend for the `index` stage (makeindex/xindy), else the
   * bundled makeindex WASM (client-first, fully on-device) — and inject it so `\printindex`
   * resolves on the next pass. Gated on the source actually using `\makeindex`+`\printindex`
   * so a stale `.idx` in a reused engine can't add a phantom index.
   * @returns whether a fresh `.ind` was injected this pass (forces one more LaTeX pass).
   */
  async maybeRunMakeindex(e) {
    const i = this.engine;
    if (!i || !e.success && !e.pdf || !u(this.mainSource())) return !1;
    const t = this.mainFile.replace(/\.tex$/, "");
    if (this.fs.readFile(`${t}.ind`)) return !1;
    const n = await i.readFile(`${t}.idx`);
    if (!n?.trim()) return !1;
    const s = { idx: n }, a = await T(this.opts.backends, s) ?? await this.runClientMakeindex(t, n), r = {
      stage: "index",
      projectInputs: [],
      complete: !!a
    };
    if (this.currentAuxiliaryDependencies.set("index", r), !a) return !1;
    const o = `${t}.ind`, l = h(o) ?? o;
    return this.fs.writeFile(o, a), this.generatedFiles.add(l), this.generatedDependencyObservations.set(l, r), await i.writeFile(o, a), !0;
  }
  /** Resolve the project-local custom `.bst` named by `\bibliographystyle` (read from the
   *  VFS), or null when the style is bundled / absent. Shared by the client + server paths. */
  resolveProjectBst(e) {
    return v(e, (i) => {
      const t = this.fs.readFile(i);
      return typeof t == "string" ? t : null;
    });
  }
  /** Gather the project's `.bib` databases (path → content) for the bibliography stage. */
  collectBibFiles() {
    const e = {};
    for (const i of this.fs.listFiles()) {
      if (!i.endsWith(".bib")) continue;
      const t = this.fs.readFile(i);
      typeof t == "string" && (e[i] = t);
    }
    return e;
  }
  /** Run the bundled client BibTeX (WASM) engine for the bibliography stage → `.bbl`, or
   *  null if it produced none. The default when no server backend is registered. */
  async runClientBibtex(e, i, t) {
    const n = await this.ensureBibtexEngine();
    await n.writeFile(`${e}.aux`, i);
    for (const [a, r] of Object.entries(t))
      await n.writeFile(a, r);
    const s = this.resolveProjectBst(i);
    return s && await n.writeFile(s.path, s.content), await n.compile(e), await n.readFile(`${e}.bbl`) ?? null;
  }
  /** Shared constructor options for the bundled aux-stage engines (BibTeX, makeindex):
   *  same asset base / TeX Live version / endpoint as the main engine. */
  auxEngineOpts() {
    const e = {
      assetBaseUrl: this.assetBaseUrl,
      texliveVersion: this.opts.texliveVersion ?? "2025"
    };
    return this.opts.texliveUrl && (e.texliveUrl = this.opts.texliveUrl), e;
  }
  async ensureBibtexEngine() {
    if (this.bibtexEngine) return this.bibtexEngine;
    const e = new M(this.auxEngineOpts());
    return await e.init(), this.bibtexEngine = e, e;
  }
  /** Run the bundled client makeindex (WASM) engine for the index stage → `.ind`, or null
   *  if it produced none. The default when no server backend is registered for `index`. */
  async runClientMakeindex(e, i) {
    const t = await this.ensureMakeindexEngine();
    return await t.writeFile(`${e}.idx`, i), await t.compile(e), await t.readFile(`${e}.ind`) ?? null;
  }
  async ensureMakeindexEngine() {
    if (this.makeindexEngine) return this.makeindexEngine;
    const e = new A(this.auxEngineOpts());
    return await e.init(), this.makeindexEngine = e, e;
  }
  ensureInitialized() {
    if (!this.initialized)
      throw new Error("WasmTexCompiler is not initialized. Call init() first.");
  }
}
export {
  ve as BIBER_STAGE,
  ge as BIBLIOGRAPHY_STAGE,
  Me as BIBTEX_STAGE,
  Se as BackendRegistry,
  ye as COMPLETION_SNAPSHOT_MAX_ESTIMATED_BYTES,
  we as COMPLETION_SNAPSHOT_SCHEMA_VERSION,
  Ie as INDEX_STAGE,
  Oe as MemoryCacheStore,
  de as WasmTexCompiler,
  Pe as backendCacheKey,
  be as biblatexLiteBackend,
  Te as contentKey,
  ue as createBiberBackend,
  De as createJsonTextBackend,
  Be as createMakeindexBackend,
  ke as createRemoteBackend,
  Re as createXindyBackend,
  w as detectBiblatexBackend,
  C as detectBiblatexSort,
  y as detectBibliographyMode,
  u as detectIndexUse,
  B as generateBiblatexBbl,
  E as parseBcfCitedKeys,
  x as runRemoteBiber,
  F as runRemoteBibliography,
  T as runRemoteIndex,
  xe as selectBiblatexBackend,
  Ae as withCache
};
